# Flavor-Blind fNP Configuration for TMD PDFs and FFs
# Based on MAP22 parameterization from NangaParbat
# Author: Chiara Bissolotti (cbissolotti@anl.gov)
#
# FLAVOR-BLIND SYSTEM:
# All flavors (u, d, s, ubar, dbar, sbar, c, cbar) share IDENTICAL parameters.
# When parameters are updated during fitting, ALL flavors change simultaneously.
# This dramatically reduces the parameter count while maintaining the full TMD structure.

# Global settings
hadron: proton
zeta: 1.0  # Reference rapidity scale in GeV^2

# Shared evolution factor (applies to both PDFs and FFs)
evolution:
  init_g2: 0.12840      # Evolution parameter g₂ (from MAP22)
  free_mask: [true]     # g2 is trainable

# TMD PDF parameterization (MAP22 implementation)
# Parameters: [N1, \alpha_1, \sigma_1, \lambda, N_{1\beta}, N1C, \lambda_2, |alpha_2, α₃, σ₂, σ₃] (11 params)
# 
# IMPORTANT: This single parameter set applies to ALL PDF flavors:
# u, d, s, ubar, dbar, sbar, c, cbar will all have identical shapes
pdf:
  # Universal parameters for ALL PDF flavors
  init_params: [0.28516, 2.9755, 0.17293, 0.39432, 0.28516, 0.28516, 0.39432, 2.9755, 2.9755, 0.17293, 0.17293]
  free_mask: [true, true, true, true, true, true, true, true, true, true, true]

# TMD FF parameterization (MAP22 implementation)  
# Parameters: [N3, \beta_1, \sigma_1, \gamma_1, \lambda_F, N_{3\beta}, \beta_2, \sigma_2, \gamma_2] (9 params)
#
# IMPORTANT: This single parameter set applies to ALL FF flavors:
# u, d, s, ubar, dbar, sbar, c, cbar will all have identical fragmentation shapes
ff:
  # Universal parameters for ALL FF flavors
  init_params: [0.21012, 2.12062, 0.093554, 0.25246, 5.2915, 0.033798, 2.1012, 0.093554, 0.25246]
  free_mask: [true, true, true, true, true, true, true, true, true]

# Parameter Summary for Flavor-Blind System:
# ==========================================
# Evolution: 1 parameter (g2)
# PDF: 11 parameters (shared across ALL 8 flavors)
# FF: 9 parameters (shared across ALL 8 flavors)
# Total: 21 parameters
#
# All 21 parameters are trainable by default in this configuration.
#
# Comparison with standard system:
# - Standard: ~161 parameters (8 flavors × 11 PDF + 8 flavors × 9 FF + 1 evolution)
# - Flavor-blind: 21 parameters  
# - Parameter reduction: 87%
#
# Physical interpretation:
# - All quark flavors have identical TMD shapes in x and b_T
# - Only the collinear PDFs/FFs (from APFEL++) distinguish flavors
# - The non-perturbative contributions are universal across flavors
# - This is a strong assumption but may be reasonable for phenomenology
#
# Benefits:
# - Dramatically faster fitting (21 vs 161 parameters)
# - Reduced overfitting risk
# - Cleaner physical interpretation
# - Easier parameter analysis and uncertainty propagation
#
# Limitations:
# - Cannot capture flavor-specific TMD behavior
# - May not describe data as accurately as full flavor-dependent system
# - Less flexibility for fine-tuning individual flavors

