hadron: proton

# Energy scale in GeV at which fNP is parametrized
zeta: 1.0

# Shared evolution parameters
evolution:
  init_g2: 0.25

flavors:
  u:
    # The u‐quark parametrization requires 11 parameters:
    # [N1, alpha1, sigma1, lambda, N1B, N1C, lambda2, alpha2, alpha3, sigma2, sigma3]
    init_params: [0.25, 0.15, 0.12, 0.10, 0.20, 0.18, 0.08, 0.14, 0.13, 0.11, 0.09]
    free_mask: [true, true, false, true, true, false, true, true, true, false, true] # 8 trainable, 3 fixed
  d:
    # d‐quark parametrization (10 parameters)
    init_params: [0.25, 0.15, 0.12, 0.10, 0.20, 0.18, 0.08, 0.14, 0.13, 0.11]
    free_mask: [true, false, true, true, false, true, true, false, true, true] # 7 trainable, 3 fixed
  ubar:
    # ubar: using a 2‐parameter default
    init_params: [0.50, 0.50]
    free_mask: [true, false] # 1 trainable, 1 fixed
  dbar:
    # dbar: using a 2‐parameter default
    init_params: [0.50, 0.50]
    free_mask: [false, true] # 1 trainable, 1 fixed
